### ISSUE TITLE
Not working with Glide 4.6.1

### ISSUE THREAD

**Issue by megurupriyan** [sandrios/sandriosCamera#41]
Unable to upgrade Glide to the latest version, only supports Glide 3.8.0

` java.lang.NoSuchMethodError: No virtual method load(Landroid/net/Uri;)Lcom/bumptech/glide/DrawableTypeRequest; in class Lcom/bumptech/glide/RequestManager; or its super classes (declaration of 'com.bumptech.glide.RequestManager' appears in /data/app/com.signaltest.signaltest-2/base.apk)
                                                                             at com.sandrios.sandriosCamera.internal.ui.view.ImageGalleryAdapter.onBindViewHolder(ImageGalleryAdapter.java:133)
                                                                             at com.sandrios.sandriosCamera.internal.ui.view.ImageGalleryAdapter.onBindViewHolder(ImageGalleryAdapter.java:25)
                                                                             at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6673)
                                                                             at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6714)
                                                                             at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5647)
                                                                             at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5913)
                                                                             at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5752)
                                                                             at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5748)
                                                                             at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2232)
                                                                             at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1559)
                                                                             at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1519)
                                                                             at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:614)
                                                                             at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3812)
                                                                             at android.support.v7.widget.RecyclerView.onMeasure(RecyclerView.java:3225)`

**Comment by sharukhmohammed** [comment]
Still not yet updated.

**Comment by arpitgandhi9** [comment]
Sorry for the delay. Please update to version 1.2.6
